#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.0 on Sat Apr 10 13:04:32 2021
#
import os
import time
import threading as th
import configparser as config
import pygame
import wx
import glob as gl
from mutagen.mp3 import MP3 as mp3
from lib.ore_music_player_base import OreMusincPlayerBase
from lib.ore_music_player_base import MakePlayListDialogBase

CONFIG_FILE = "./config.ini"
conf = config.ConfigParser()
conf.read(CONFIG_FILE, encoding='utf-8')
# begin wxGlade: dependencies
# end wxGlade
# begin wxGlade: extracode
# end wxGlade


class OreMusincPlayer(OreMusincPlayerBase):
    slide_count: int
    COUNT_VALUE = float(conf['GENERAL']['ThreadSleep'])
    img_ff = conf['IMG']['ff']
    img_ff_push = conf['IMG']['ff_push']

    def __init__(self, *args, **kwds):
        super().__init__(*args, **kwds)
        self.slide_count = 0
        self.slider.SetMin(0)
        self.slider.SetMax(0)
        self.play_flag = False
        self.pause_flag = False
        self.destroy_flag = False
        self.thread = th.Thread(target=self.thread_work)
        self.thread.start()
        # self.thread = Thread(target=self.sloder_update)
        # self.thread.start()

    def show_play_list_modal(self, event):
        dialog = MakePlayListDialog(self)
        dialog.ShowModal()

    def push_button_pre(self, event):
        print("Event handler 'push_button_pre' not implemented!")
        event.Skip()

    def push_button_rew(self, event):
        if hasattr(self, "music"):
            if self.slide_count >= int(conf['GENERAL']['ChangeValueButton']):
                self.slide_count -= int(conf['GENERAL']['ChangeValueButton'])
            else:
                self.slide_count -= 0
            self.music.start(loops=0, start=self.slide_count)

    def push_button_play(self, event):
        filename = r"D:\OneDrive - SatoshiOhtomo\05_MUSIC\Dream Theater\Awake\01 6_00.mp3"
        self.play_flag = True
        self.play(file_name=filename, start=self.slider.GetValue())
        self.button_play.SetBitmap(wx.Bitmap("img/play_push.jpeg", wx.BITMAP_TYPE_ANY))
        self.button_pause.SetBitmap(wx.Bitmap("img/pause.jpeg", wx.BITMAP_TYPE_ANY))

    def push_button_stop(self, event):
        self.play_flag = False
        self.music.stop()
        self.button_play.SetBitmap(wx.Bitmap("img/play.jpeg", wx.BITMAP_TYPE_ANY))
        self.button_pause.SetBitmap(wx.Bitmap("img/pause.jpeg", wx.BITMAP_TYPE_ANY))

    def push_button_pause(self, event):
        if self.play_flag:
            if self.pause_flag:
                self.music.start(start=int(self.slider.GetValue()))
                self.pause_flag = False
                self.button_pause.SetBitmap(wx.Bitmap("img/pause.jpeg", wx.BITMAP_TYPE_ANY))
            else:
                self.music.pause()
                self.button_pause.SetBitmap(wx.Bitmap("img/pause_push.jpeg", wx.BITMAP_TYPE_ANY))
                self.pause_flag = True

    def push_button_ff(self, event):
        if hasattr(self, "music"):
            if self.slide_count + int(conf['GENERAL']['ChangeValueButton']) < self.music.length:
                self.slide_count += int(conf['GENERAL']['ChangeValueButton'])
                self.music.start(loops=0, start=self.slide_count)

    def push_button_next(self, event):
        print("Event handler 'push_button_next' not implemented!")
        event.Skip()

    def scroll_pagedown(self, event):
        if hasattr(self, "music"):
            print("aaabbbcccedd")
            if self.slide_count + int(conf['GENERAL']['ChangeValueSlider']) < self.music.length:
                self.slide_count += int(conf['GENERAL']['ChangeValueSlider'])
                self.music.start(loops=0, start=self.slide_count)

    def scroll_pageup(self, event):
        if hasattr(self, "music"):
            print("asfdasdf")
            if self.slide_count >= int(conf['GENERAL']['ChangeValueSlider']):
                self.slide_count -= int(conf['GENERAL']['ChangeValueSlider'])
            else:
                self.slide_count -= 0
            self.music.start(loops=0, start=self.slide_count)


    def slider_ctrl(self, event):
        self.play_flag = False
        self.pause_flag = True

    def push_rep_start(self, event):
        self.text_ctrl_rep_start.SetValue(str(self.slider.GetValue()))

    def push_rep_end(self, event):
        self.text_ctrl_rep_end.SetValue(str(self.slider.GetValue()))

    def push_toggle_rep(self, event):  # wxGlade: OreMusincPlayerBase.<event_handler>
        self.slide_count = int(self.text_ctrl_rep_start.GetValue())
        self.music.start(loops=0, start=self.slide_count)

    def scroll_changed(self, event):
        self.slide_count = int(self.slider.GetValue())
        self.music.start(loops=0, start=self.slide_count)
        self.play_flag = True
        self.pause_flag = False

    def play(self, file_name, start, loops=0):
        self.music = self.Music(file_name)
        self.slider.SetMin(0)
        self.slider.SetMax(int(self.music.length))
        self.music.start(loops=loops, start=start)
        self.slide_count = start
        self.play_flag = True
        self.pause_flag = False

    def thread_work(self):
        while True:
            if self.destroy_flag:
                break
            time.sleep(self.COUNT_VALUE)
            if not hasattr(self, "music") or not self.play_flag:
                continue
            self.slider.SetValue(int(self.slide_count))

            max_count = 0
            if self.button_rep_start_toggle.GetValue():
                max_count = int(self.text_ctrl_rep_end.GetValue())
            else:
                max_count = self.music.length

            if self.play_flag and not self.pause_flag:
                if self.slide_count <= max_count:
                    self.slide_count += self.COUNT_VALUE
                else:
                    if self.button_rep_start_toggle.GetValue():
                        self.slide_count = int(self.text_ctrl_rep_start.GetValue())
                        self.music.start(loops=0, start=self.slide_count)
                    else:
                        self.button_play.SetBitmap(wx.Bitmap("img/play.jpeg", wx.BITMAP_TYPE_ANY))

    def Destroy(self):
        self.destroy_flag = True
        return super().Destroy()

    class Music():
        def __init__(self, file_name):
            pygame.mixer.init()
            pygame.mixer.music.load(file_name)
            self.length = mp3(file_name).info.length

        def start(self, loops=0, start=0):
            pygame.mixer.music.play(loops=loops, start=start)

        def stop(self):
            pygame.mixer.music.stop()

        def pause(self):
            pygame.mixer.music.pause()


class OreMusicPlayer(wx.App):
    def OnInit(self):
        self.frame = OreMusincPlayer(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class OreMusicPlayerBase


class MakePlayListDialog(MakePlayListDialogBase):
    def __init__(self, *args, **kwds):
        super().__init__(*args, **kwds)
        imageList = wx.ImageList(16, 16)
        idx1 = imageList.Add(wx.ArtProvider.GetBitmap(wx.ART_FOLDER, wx.ART_OTHER, (16, 16)))
        idx2 = imageList.Add((wx.ArtProvider.GetBitmap(wx.ART_NEW, wx.ART_OTHER, (16, 16))))
        self.folder_tree.AssignImageList(imageList)
        tree_dict = {}
        for full_path in gl.glob(r"D:\OneDrive - SatoshiOhtomo\05_MUSIC\**\*mp3", recursive=True):
            if os.path.isdir(full_path):
                continue
            key = ""
            item = None
            counter = 0
            for d in full_path.split(os.sep):
                key = os.path.join(key, d) if counter > 0 else "{}{}".format(d, os.sep)
                if key in tree_dict:
                    item = tree_dict[key]
                else:
                    if counter == 0:
                        item = self.folder_tree.AddRoot(d, idx1, -1, None)
                    else:
                        if os.path.isdir(key):
                            item = self.folder_tree.AppendItem(item, d, idx1, -1, None)
                        else:
                            item = self.folder_tree.AppendItem(item, d, idx2, -1, None)
                counter += 1
                tree_dict[key] = item


if __name__ == "__main__":
    app = OreMusicPlayer(0)
    app.MainLoop()
