#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.0 on Sat Apr 10 13:04:32 2021
#
import os
import pathlib
import time
import threading as th
import configparser as config
import wx
import glob as gl
import re
import pygame.mixer
import datetime as dt
from mutagen.mp3 import MP3
from lib.ore_music_player_base import OreMusincPlayerBase
from lib.ore_music_player_base import MakePlayListDialogBase

CONFIG_FILE = "./config.ini"
conf = config.ConfigParser()
conf.read(CONFIG_FILE, encoding='utf-8')
# begin wxGlade: dependencies
# end wxGlade
# begin wxGlade: extracode
# end wxGlade


class OreMusincPlayer(OreMusincPlayerBase):
    slide_count: int
    COUNT_VALUE = float(conf['GENERAL']['ThreadSleep'])
    img_ff = conf['IMG']['ff']
    img_ff_push = conf['IMG']['ff_push']

    def __init__(self, *args, **kwds):
        super().__init__(*args, **kwds)
        self.slide_count = 0
        self.slider.SetMin(0)
        self.slider.SetMax(0)
        self.play_flag = False
        self.pause_flag = False
        self.destroy_flag = False
        self.thread = th.Thread(target=self.thread_work)
        self.thread.start()
        self.make_tree_list(conf['GENERAL']['RootDir'])
        self.music = None
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap(r"img/icon.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

    def show_play_list_modal(self, event):
        dialog = MakePlayListDialog(self)
        dialog.ShowModal()

    def push_button_pre(self, event):
        print("Event handler 'push_button_pre' not implemented!")
        event.Skip()

    def push_button_rew(self, event):
        if hasattr(self, "music"):
            if self.slide_count >= int(conf['GENERAL']['ChangeValueButton']):
                self.slide_count -= int(conf['GENERAL']['ChangeValueButton'])
            else:
                self.slide_count -= 0
            self.music.play(loops=0, start=self.slide_count)

    def push_button_play(self, event):
        self.play_music(event=event)

    def push_button_stop(self, event):
        self.play_flag = False
        self.music.stop()
        self.button_play.SetBitmap(wx.Bitmap("img/play.jpeg", wx.BITMAP_TYPE_ANY))
        self.button_pause.SetBitmap(wx.Bitmap("img/pause.jpeg", wx.BITMAP_TYPE_ANY))

    def push_button_pause(self, event):
        if self.play_flag:
            if self.pause_flag:
                self.music.play(start=int(self.slider.GetValue()))
                self.pause_flag = False
                self.button_pause.SetBitmap(wx.Bitmap("img/pause.jpeg", wx.BITMAP_TYPE_ANY))
            else:
                self.music.pause()
                self.button_pause.SetBitmap(wx.Bitmap("img/pause_push.jpeg", wx.BITMAP_TYPE_ANY))
                self.pause_flag = True

    def push_button_ff(self, event):
        if hasattr(self, "music"):
            if self.slide_count + int(conf['GENERAL']['ChangeValueButton']) < self.music.audio_file.duration:
                self.slide_count += int(conf['GENERAL']['ChangeValueButton'])
                self.music.play(loops=0, start=self.slide_count)

    def push_button_next(self, event):
        print("Event handler 'push_button_next' not implemented!")
        event.Skip()

    def scroll_pagedown(self, event):
        if hasattr(self, "music"):
            if self.slide_count + int(conf['GENERAL']['ChangeValueSlider']) < self.music.audio_file.duration:
                self.slide_count += int(conf['GENERAL']['ChangeValueSlider'])
                self.music.play(loops=0, start=self.slide_count)

    def scroll_pageup(self, event):
        if hasattr(self, "music"):
            if self.slide_count >= int(conf['GENERAL']['ChangeValueSlider']):
                self.slide_count -= int(conf['GENERAL']['ChangeValueSlider'])
            else:
                self.slide_count -= 0
            self.music.play(loops=0, start=self.slide_count)


    def push_rep_start(self, event):
        self.text_ctrl_rep_start.SetValue(str(self.slider.GetValue()))

    def push_rep_end(self, event):
        self.text_ctrl_rep_end.SetValue(str(self.slider.GetValue()))

    def push_toggle_rep(self, event):  # wxGlade: OreMusincPlayerBase.<event_handler>
        self.slide_count = int(self.text_ctrl_rep_start.GetValue())
        self.music.play(loops=0, start=self.slide_count)

    def slider_ctrl(self, event):
        self.play_flag = False
        self.pause_flag = True

    def scroll_changed(self, event):
        self.slide_count = int(self.slider.GetValue())
        self.music.play(loops=0, start=self.slide_count)
        self.play_flag = True
        self.pause_flag = False

    def thread_work(self):
        while True:
            if self.destroy_flag:
                break
            time.sleep(self.COUNT_VALUE)
            if not hasattr(self, "music") or not self.play_flag:
                continue
            self.slider.SetValue(int(self.slide_count))

            max_count = 0
            if self.button_rep_start_toggle.GetValue():
                max_count = int(self.text_ctrl_rep_end.GetValue())
            else:
                max_count = self.music.audio_file.duration

            if self.play_flag and not self.pause_flag:
                if self.slide_count <= max_count:
                    self.slide_count += self.COUNT_VALUE
                else:
                    if self.button_rep_start_toggle.GetValue():
                        self.slide_count = int(self.text_ctrl_rep_start.GetValue())
                        self.music.play(loops=0, start=self.slide_count)
                    else:
                        self.button_play.SetBitmap(wx.Bitmap("img/play.jpeg", wx.BITMAP_TYPE_ANY))

    def play_music(self, event):
        elem_id = self.list_ctrl_music_list.GetFirstSelected()
        file_path = "{}.{}".format(
            os.path.join(
                self.list_ctrl_music_list.GetItemText(elem_id, 3),
                self.list_ctrl_music_list.GetItemText(elem_id, 0)
            ),
            self.list_ctrl_music_list.GetItemText(elem_id, 2)
        )
        audio_file = AudioFile(file_path)
        self.music = MusicPlayer(audio_file)
        self.play_flag = True
        self.pause_flag = False
        self.slider.SetMin(0)
        self.slider.SetMax(int(self.music.audio_file.duration))
        self.slide_count = 0
        self.button_play.SetBitmap(wx.Bitmap("img/play_push.jpeg", wx.BITMAP_TYPE_ANY))
        self.button_pause.SetBitmap(wx.Bitmap("img/pause.jpeg", wx.BITMAP_TYPE_ANY))
        self.music.play()

    def make_tree_list(self, root_dir="./"):
        image_list = wx.ImageList(16, 16)
        idx1 = image_list.Add(wx.ArtProvider.GetBitmap(wx.ART_FOLDER, wx.ART_OTHER, (16, 16)))
        self.folder_tree.AssignImageList(image_list)
        tree_dict = {}
        item = None
        root = None
        for full_path in gl.glob(os.path.join(root_dir, "**"), recursive=True):
            if os.path.isfile(full_path):
                continue
            key = ""
            if pathlib.Path(full_path).resolve() == pathlib.Path(root_dir).resolve():
                root = self.folder_tree.AddRoot(root_dir, idx1, -1, full_path)
                continue
            p_path = pathlib.Path(full_path).relative_to(root_dir)
            label = p_path.name
            if len(p_path.parts) > 1:
                for d in p_path.parts:
                    key = os.path.join(key, d)
                    if key in tree_dict:
                        item = tree_dict[key]
                        label = p_path.name.split(os.sep)[-1]
            else:
                item = root
            tree_dict[str(p_path)] = self.folder_tree.AppendItem(item, label, idx1, -1, full_path)
        self.folder_tree.Expand(root)

    def select_folder(self, event):
        reg = re.compile(conf['SOUND']['EXT'])
        path_list = [self.folder_tree.GetItemData(item) for item in self.folder_tree.GetSelections()]
        audio_files = []
        for path in path_list:
            audio_files.append([AudioFile(str(file_name)) for file_name in [file_name for file_name in pathlib.Path(path).glob('*') if re.search(reg, str(file_name))]])
        audio_files = sum(audio_files, [])
        self.list_ctrl_music_list.DeleteAllItems()
        for audio_file in audio_files:
            h, m, s = self.num_to_time(audio_file.duration)
            self.list_ctrl_music_list.Append([audio_file.file_name, "{:02}:{:02}:{:02}".format(h, m, s), str(audio_file.ext).replace(".", ""), audio_file.dir_name])

    def num_to_time(self, num):
        td = dt.timedelta(seconds=num)
        m, s = divmod(td.seconds, 60)
        h, m = divmod(m, 60)
        return h, m, s

    def Destroy(self):
        self.destroy_flag = True
        return super().Destroy()


class AudioFile:
    def __init__(self, file_path):
        self.dir_name = os.path.dirname(file_path)
        self.file_name ,self.ext = os.path.splitext(os.path.basename(file_path))
        self.duration = MP3(self.get_file_path()).info.length

    def get_file_path(self):
        return "{}{}".format(
            os.path.join(
                self.dir_name,
                self.file_name
            ),
            self.ext
        )


class MusicPlayer:
    def __init__(self, audio_file=None):
        pygame.mixer.init(frequency=int(conf['SOUND']['Frequency']))
        self.audio_file = None
        self.load(audio_file)

    def load(self, audio_file=None):
        if audio_file:
            self.audio_file = audio_file
            pygame.mixer.music.load(self.audio_file.get_file_path())

    def play(self, loops=0, start=0):
        pygame.mixer.music.play(loops=loops, start=start)

    def stop(self):
        pygame.mixer.music.stop()

    def pause(self):
        pygame.mixer.music.pause()


class OreMusicPlayer(wx.App):
    def OnInit(self):
        self.frame = OreMusincPlayer(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class OreMusicPlayerBase


class MakePlayListDialog(MakePlayListDialogBase):
    def __init__(self, *args, **kwds):
        super().__init__(*args, **kwds)
        imageList = wx.ImageList(16, 16)
        idx1 = imageList.Add(wx.ArtProvider.GetBitmap(wx.ART_FOLDER, wx.ART_OTHER, (16, 16)))
        idx2 = imageList.Add((wx.ArtProvider.GetBitmap(wx.ART_NEW, wx.ART_OTHER, (16, 16))))
        self.folder_tree.AssignImageList(imageList)
        tree_dict = {}
        for full_path in gl.glob(r"D:\OneDrive - SatoshiOhtomo\05_MUSIC\**\*mp3", recursive=True):
            if os.path.isdir(full_path):
                continue
            key = ""
            item = None
            counter = 0
            for d in full_path.split(os.sep):
                key = os.path.join(key, d) if counter > 0 else "{}{}".format(d, os.sep)
                if key in tree_dict:
                    item = tree_dict[key]
                else:
                    if counter == 0:
                        item = self.folder_tree.AddRoot(d, idx1, -1, None)
                    else:
                        if os.path.isdir(key):
                            item = self.folder_tree.AppendItem(item, d, idx1, -1, None)
                        else:
                            item = self.folder_tree.AppendItem(item, d, idx2, -1, None)
                counter += 1
                tree_dict[key] = item

    def tree_drag(self, event):
        for item in self.folder_tree.GetSelections():
            print(item.GetID())

    def save_play_list(self, event):
        self.folder_tree


if __name__ == "__main__":
    app = OreMusicPlayer(0)
    app.MainLoop()
